### ISSUE TITLE
Add audio visualizer while the user is speaking.

### ISSUE THREAD

**Issue by Karthik-Sarvan** [Karthik-Sarvan/Luna_Voice#4]

**Comment by Nisha-Rao21** [comment]
Hi @Karthik-Sarvan, I would like to work on this. Wanted to know where should the visualizer be placed

**Comment by Karthik-Sarvan** [comment]
okay make the mic hidden and place the visualizer.

**Comment by Nisha-Rao21** [comment]
@Karthik-Sarvan, if I hide the mic button, how would the user stop the recording?

**Comment by Karthik-Sarvan** [comment]
@Nisha-Rao21  okay. make the "stop recording" option to the side.
